# -*- coding: utf-8 -*-
"""practical 8.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rCnYkGqfn7P0uD7QE6qKgBdtKevrBFaW
"""

#arithmetic operations between two set
#union
#set1.union(set2)- used to add two set
set1={1,2,3,4}
set2={3,4,5,6}
set1.union(set2)

#intersection
#set1.intersection(set2)- give common element
set1={1,2,3,4}
set2={3,4,5,6}
set1.intersection(set2)

# difference - give elements in the set1 that are not present in set2
set1={1,2,3,4}
set2={3,4,5,6}
set1.difference(set2)

# symmetric difference- give elemets that are not common in both set
set1={1,2,3,4}
set2={3,4,5,6}
set1.symmetric_difference(set2)

#frozenset -do not allow addition or removal of elements but it allow union,intersection,
#difference and symmetric difference between two elements
#set- allow addition and removal of elements

#loops-execute a block of code multiple times
#for and while
#for

a=int(input())
for i in range (1,11):
  print(f"{a} * {i} = {a*i}" )

#tuple
a=(1,2,3,4)
for i in (a):
 print(i)

#list
a=[11,2,3,4]
for i in (a):
 print(i)

#dictionary
a={'name':'anita','roll no':2}
for i in (a):
 print(i)

#dictionary
a={'name':'anita','roll no':2}
for i in a.values():
 print(i)

#dictionary
a={'name':'anita','roll no':2}
for i in a.items():
 print(i)

name='anita'
for i in name:
 print(i)

roll ='1234'
for i in roll:
 print(i)